
all:

test/config/ssh.key:
	ssh-keygen -t rsa -f test/config/ssh -N '' -C 'Test key'
	mv test/config/ssh test/config/ssh.key


test/config/munge.key:
	dd if=/dev/urandom bs=1 count=1024 > test/config/munge.key 

testprep: test/config/ssh.key test/config/munge.key
	docker volume inspect imagegw || docker volume create --name imagegw

startdeps:
	docker run -d --name mongot -p 27017:27017 mongo --smallfiles

starttest: testprep
	docker build -t imagegwapi .
	docker build -t shifter-test ..
	docker-compose up -d

restartgw:
	docker build -t imagegwapi .
	docker-compose up -d

#	$(eval IP=$(shell docker-machine ip $(shell docker-machine active)))
#	@echo "ssh -i test/config/ssh.key $(IP) -p $(PORT)"
getssh:
	$(eval PORT=$(shell docker-compose ps systema|grep systema|sed 's/.*://'|sed 's/-.*//'))
	@docker inspect systema | grep IPAddr
	@echo "To connect, do:"
	@echo "ssh -i test/config/ssh.key root@localhost -p $(PORT)"
	@echo "  --or--"
	@echo "ssh -i test/config/ssh.key root@172.17.0.x -p $(PORT)"

cleanup:
	docker-compose stop
	docker images -f dangling=true -q|xargs docker rmi
